namespace TradeDesktop.Application.Models;

public sealed record ConfigRecord(
    string Id,
    string SansJson,
    string? HostName,
    string PlatformA,
    string PlatformB,
    int Point,
    int OpenPts,
    int ConfirmGapPts,
    int HoldConfirmMs,
    int ClosePts,
    int CloseConfirmGapPts,
    int CloseHoldConfirmMs,
    int StartTimeHold,
    int EndTimeHold,
    int StartWaitTime,
    int EndWaitTime,
    int ConfirmLatencyMs,
    int MaxGap,
    int MaxSpread,
    int OpenMaxTimesTick,
    int CloseMaxTimesTick,
    int OpenPendingTimeMs,
    int ClosePendingTimeMs,
    int DelayOpenAMs,
    int DelayOpenBMs);